package vista;

import controlador.servicio.ServicioAdministrador;
import controlador.servicio.ServicioNoticia;
import controlador.utilidades.Sesiones;
import controlador.utilidades.Utilidades;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.stream.Collectors;
import javax.swing.ButtonGroup;
import javax.swing.event.ChangeEvent;
import modelo.enums.TipoNoticia;
import vista.tablas.ModeloTablaNoticias;
import vista.utilidades.UtilidadesComponente;

public class FrmComentarios extends javax.swing.JDialog {

    private ServicioNoticia sn = new ServicioNoticia();
    private ModeloTablaNoticias modelo = new ModeloTablaNoticias();

    public FrmComentarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarTabla();
        ButtonGroup botonGrupo = new ButtonGroup();
        botonGrupo.add(rdTodos);
        botonGrupo.add(rdTipos);
        mostrarCombo();
        cargarCombo();
    }
public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/avatar.png"));
        return retValue;
    }
    private void mostrarCombo() {
        if (rdTodos.isSelected()) {
            cbxTipoBuscar.setEnabled(false);
        } else if (rdTipos.isSelected()) {
            cbxTipoBuscar.setEnabled(true);
        }
    }

    private void cargarTabla() {
        modelo.setLista(sn.listado());
        tblNoticias.setModel(modelo);
        tblNoticias.updateUI();
    }

    private void buscar() {
        if (Utilidades.isEmpty(txtBuscar.getText())) {
            cargarTabla();
        } else {
            if (txtBuscar.getText().trim().length() >= 3) {
                modelo.setLista(sn.listado());
                tblNoticias.setModel(modelo);
                tblNoticias.updateUI();
            }
        }
    }

    private void buscarTipo() {
        if (txtBuscar.getText().isEmpty() || txtBuscar.getText().trim().length() >= 3) { //Buscar por tres letras ingresadas
            //trim.- Quitar espacios en blanco

        } else {

        }
    }

    private void cargarCombo() {
        UtilidadesComponente.cargarComboTipo(cbxTipoBuscar);
        cbxTipoBuscar.updateUI();
    }

//    private void cargarObjeto() {
//        sn.obtenerNoticia().setContenido(txtContenido.getText());
//        sn.obtenerNoticia().setFecha(new Date());
//        sn.obtenerNoticia().setTitulo(txtTitulo.getText());
//        sn.obtenerNoticia().setTipoNoticia((TipoNoticia) cbxTipoBuscar.getSelectedItem());
//        ServicioAdministrador sa = new ServicioAdministrador();
//        sa.obtenerAdministrador().setId(Sesiones.getSesion().getId());
//        sn.obtenerNoticia().setAdministrador(sa.obtenerAdministrador());
//    }
//
//    private void limpiar() {
//        sn.fijarInstancia(null);
//        txtTitulo.setText(null);
//        txtContenido.setText(null);
//        cbxTipoBuscar.setSelectedIndex(0);
//    }
//
//    private void cargarVista() {
//        int fila = -1;
//        fila = tblNoticias.getSelectedRow();
//        if (fila < 0) {
//            UtilidadesComponente.mensajeError("Error", "Se debe escoger una Noticia de la tabla");
//        } else {
//            sn.fijarInstancia(modelo.getLista().get(fila));
//            txtContenido.setText(sn.obtenerNoticia().getContenido());
//            txtTitulo.setText(sn.obtenerNoticia().getTitulo());
//            cbxTipoBuscar.setSelectedItem(sn.obtenerNoticia().getTipoNoticia());
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNoticias = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbxTipoBuscar = new javax.swing.JComboBox<>();
        rdTipos = new javax.swing.JRadioButton();
        rdTodos = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Noticias");
        setIconImage(getIconImage());
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Listado de Noticias"));
        jPanel2.setLayout(null);

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel2.add(txtBuscar);
        txtBuscar.setBounds(270, 30, 200, 20);

        tblNoticias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNoticias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNoticiasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNoticias);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 452, 130);

        jLabel2.setText("Buscar:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 30, 50, 20);

        cbxTipoBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbxTipoBuscar);
        cbxTipoBuscar.setBounds(170, 30, 100, 20);

        rdTipos.setText("Tipos");
        rdTipos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdTiposStateChanged(evt);
            }
        });
        jPanel2.add(rdTipos);
        rdTipos.setBounds(120, 30, 50, 20);

        rdTodos.setSelected(true);
        rdTodos.setText("Todos");
        rdTodos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdTodosStateChanged(evt);
            }
        });
        jPanel2.add(rdTodos);
        rdTodos.setBounds(60, 30, 60, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 10, 490, 200);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Noticia"));
        jPanel3.setLayout(null);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelar);
        btnCancelar.setBounds(280, 220, 100, 30);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(btnGuardar);
        btnGuardar.setBounds(100, 220, 110, 30);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(30, 210, 430, 10);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 250, 490, 260);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(310, 220, 73, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 530, 520);

        setSize(new java.awt.Dimension(546, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
//        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
//        if (Utilidades.isEmpty(txtTitulo.getText()) || Utilidades.isEmpty(txtContenido.getText())) {
//            UtilidadesComponente.mensajeError("Error", "Algunos campos son obligatorios");
//        } else {
//            cargarObjeto();
//            if (sn.obtenerNoticia().getId() != null) {
//                //modificar
//                if (sn.guardar()) {
//                    UtilidadesComponente.mensajeOK("Aviso", "Se ha modificado correctamente");
//                    limpiar();
//                    cargarTabla();
//                } else {
//                    UtilidadesComponente.mensajeError("Error", "No se ha podido modificar");
//                }
//            } else {
//                //guardar
//                if (sn.guardar()) {
//                    UtilidadesComponente.mensajeOK("Aviso", "Se ha guardado correctamente");
//                    limpiar();
//                    cargarTabla();
//                } else {
//                    UtilidadesComponente.mensajeError("Error", "No se ha podido guardar");
//                }
//            }
//        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        //this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tblNoticiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNoticiasMouseClicked
//        if (evt.getClickCount() >= 2) {
//            cargarVista();
//        }
    }//GEN-LAST:event_tblNoticiasMouseClicked

    private void rdTodosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdTodosStateChanged
        mostrarCombo();
    }//GEN-LAST:event_rdTodosStateChanged

    private void rdTiposStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdTiposStateChanged
        mostrarCombo();
    }//GEN-LAST:event_rdTiposStateChanged

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        buscar();
    }//GEN-LAST:event_txtBuscarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmComentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmComentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmComentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmComentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmComentarios dialog = new FrmComentarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxTipoBuscar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rdTipos;
    private javax.swing.JRadioButton rdTodos;
    private javax.swing.JTable tblNoticias;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
