/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.servicio.ServicioAdministrador;
import controlador.utilidades.Sesiones;
import controlador.utilidades.Utilidades;
import java.awt.Dimension;
import vista.utilidades.UtilidadesComponente;
import java.awt.Image;
import java.awt.Toolkit;
/**
 *
 * @author Víctor Andrés Rojas
 */
public class FrmLogin extends javax.swing.JDialog {

    private ServicioAdministrador servicioAdministrador = new ServicioAdministrador();

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/avatar.png"));
        return retValue;
    }
    private void iniciar() {
        //Primera Forma de Mostrar Error
        if (Utilidades.isEmpty(txtUsuario.getText())
                || Utilidades.isEmpty(String.valueOf(txtClave.getPassword()))) {
            //valueOf.- Transformar a String
            UtilidadesComponente.mensajeError("Error", "Faltan campos por llenar");
        } else {
            Sesiones.setSesion(servicioAdministrador.inicioSesion(txtUsuario.getText().trim(), String.valueOf(txtClave.getPassword())));
            if (Sesiones.getSesion() != null) {
                UtilidadesComponente.mensajeOK("Bienvenido", "Bienvenido " + Sesiones.getSesion().getNombre());
                new FrmPrincipal().setVisible(true);
                this.dispose(); //dispose.-Cierra y no destruye el sistema
            } else {
                UtilidadesComponente.mensajeError("Error", "El usuario o la contraseña no son válidos");
            }
        }
        //Segunda Forma de Mostrar Error
//        if (!UtilidadesComponente.mostrarError(txtUsuario, "Faltan llnar campos", 'r') && !UtilidadesComponente.mostrarError(txtClave, "Faltan llnar campos", 'r')) {
//            //Iniciar Sesión
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        pnlInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtClave = new javax.swing.JPasswordField();
        btnSalir = new javax.swing.JButton();
        btnIniciarSesion = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnInvitado = new javax.swing.JButton();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/VentanasSimbolo.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Noticias Tercero \"B\"");
        setIconImage(getIconImage());
        setUndecorated(true);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        getContentPane().setLayout(null);

        pnlInicio.setBackground(new java.awt.Color(0, 0, 51));
        pnlInicio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlInicio.setForeground(new java.awt.Color(0, 0, 102));
        pnlInicio.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 144, 255));
        jLabel1.setText("Iniciar Sesion");
        pnlInicio.add(jLabel1);
        jLabel1.setBounds(90, 20, 160, 20);

        jLabel2.setForeground(new java.awt.Color(178, 34, 34));
        jLabel2.setText("Usuario");
        pnlInicio.add(jLabel2);
        jLabel2.setBounds(80, 200, 60, 20);

        jLabel3.setForeground(new java.awt.Color(178, 34, 34));
        jLabel3.setText("Clave");
        pnlInicio.add(jLabel3);
        jLabel3.setBounds(240, 200, 50, 20);

        txtUsuario.setBackground(new java.awt.Color(0, 0, 153));
        txtUsuario.setFont(new java.awt.Font("Elephant", 2, 14)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        pnlInicio.add(txtUsuario);
        txtUsuario.setBounds(80, 230, 120, 20);

        txtClave.setBackground(new java.awt.Color(0, 0, 153));
        txtClave.setFont(new java.awt.Font("Elephant", 2, 14)); // NOI18N
        txtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveActionPerformed(evt);
            }
        });
        pnlInicio.add(txtClave);
        txtClave.setBounds(240, 230, 120, 20);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        pnlInicio.add(btnSalir);
        btnSalir.setBounds(230, 290, 90, 30);

        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        pnlInicio.add(btnIniciarSesion);
        btnIniciarSesion.setBounds(70, 290, 110, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/User.png"))); // NOI18N
        pnlInicio.add(jLabel5);
        jLabel5.setBounds(60, 40, 240, 160);
        pnlInicio.add(jSeparator1);
        jSeparator1.setBounds(40, 260, 320, 10);

        btnInvitado.setText("Invitado");
        btnInvitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvitadoActionPerformed(evt);
            }
        });
        pnlInicio.add(btnInvitado);
        btnInvitado.setBounds(260, 0, 80, 20);

        getContentPane().add(pnlInicio);
        pnlInicio.setBounds(0, 0, 380, 340);

        setSize(new java.awt.Dimension(378, 335));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        iniciar();
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        iniciar();
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveActionPerformed
        iniciar();
    }//GEN-LAST:event_txtClaveActionPerformed

    private void btnInvitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvitadoActionPerformed
        this.dispose();
        new FrmPrincipal().setVisible(true);
    }//GEN-LAST:event_btnInvitadoActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        System.out.println("Hola");
        Dimension pantallaTamaño=this.getSize();
        pnlInicio.setLocation((pantallaTamaño.width/2)-(pnlInicio.getWidth())/2,
                (pantallaTamaño.height/2)-(pnlInicio.getHeight()/2));
        System.out.println(pantallaTamaño.height+ " " +pantallaTamaño.width);
    }//GEN-LAST:event_formWindowStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmLogin dialog = new FrmLogin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnInvitado;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlInicio;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
