/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.servicio.ServicioAdministrador;
import controlador.servicio.ServicioNoticia;
import controlador.utilidades.Sesiones;
import controlador.utilidades.Utilidades;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.enums.TipoNoticia;
import vista.tablas.ModeloTablaNoticias;
import vista.utilidades.UtilidadesComponente;

/**
 *
 * @author Víctor Andrés Rojas
 */
public class FrmNoticias extends javax.swing.JDialog {

    private ServicioNoticia sn = new ServicioNoticia();
    private ModeloTablaNoticias modelo = new ModeloTablaNoticias();

    /**
     * Creates new form FrmNoticias
     */
    public FrmNoticias(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarTabla();
        cargarCombo();
    }
public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/avatar.png"));
        return retValue;
    }
    private void cargarTabla() {
        modelo.setLista(sn.listarNoticiaAdministrador(Sesiones.getSesion().getId()));
        tblNoticias.setModel(modelo);
        tblNoticias.updateUI();
    }

    private void cargarCombo() {
        UtilidadesComponente.cargarComboTipo(cbxTipoNoticia);
        cbxTipoNoticia.updateUI();
    }

    private void buscar() {
        if (Utilidades.isEmpty(txtBuscar.getText())) {
            cargarTabla();
        } else {
            if (txtBuscar.getText().trim().length() >= 3) {
                modelo.setLista(sn.listarNoticiaAdministradorBusqueda(Sesiones.getSesion().getId(), txtBuscar.getText()));
                tblNoticias.setModel(modelo);
                tblNoticias.updateUI();
            }
        }
    }

    private void cargarObjeto() {
        sn.obtenerNoticia().setContenido(txtContenido.getText());
        sn.obtenerNoticia().setFecha(new Date());
        sn.obtenerNoticia().setTitulo(txtTitulo.getText());
        sn.obtenerNoticia().setTipoNoticia((TipoNoticia) cbxTipoNoticia.getSelectedItem());
        ServicioAdministrador sa = new ServicioAdministrador();
        sa.obtenerAdministrador().setId(Sesiones.getSesion().getId());
        sn.obtenerNoticia().setAdministrador(sa.obtenerAdministrador());
    }

    private void limpiar() {
        sn.fijarInstancia(null);
        txtTitulo.setText(null);
        txtContenido.setText(null);
        txtBuscar.setText(null);
        cbxTipoNoticia.setSelectedIndex(0);
    }

    private void cargarEdicion() {
        int fila = -1;
        fila = tblNoticias.getSelectedRow();
        if (fila < 0) {
            UtilidadesComponente.mensajeError("Error", "Se debe escoger una Noticia de la tabla");
        } else {
            sn.fijarInstancia(modelo.getLista().get(fila));
            txtContenido.setText(sn.obtenerNoticia().getContenido());
            txtTitulo.setText(sn.obtenerNoticia().getTitulo());
            cbxTipoNoticia.setSelectedItem(sn.obtenerNoticia().getTipoNoticia());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNoticias = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtContenido = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtTitulo = new javax.swing.JTextArea();
        cbxTipoNoticia = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnSalir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Noticias");
        setIconImage(getIconImage());
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Listado de Noticias"));
        jPanel2.setLayout(null);

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel2.add(txtBuscar);
        txtBuscar.setBounds(130, 30, 300, 20);

        tblNoticias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNoticias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNoticiasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNoticias);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 452, 140);

        jLabel2.setText("Buscar:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(80, 30, 50, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 10, 490, 210);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Noticia"));
        jPanel3.setLayout(null);

        jLabel1.setText("Tipo de Noticia");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(30, 170, 80, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Registro de Noticias");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(190, 20, 120, 20);

        jLabel4.setText("Título");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 50, 50, 30);

        jLabel5.setText("Contenido");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 110, 60, 20);

        txtContenido.setColumns(20);
        txtContenido.setRows(5);
        jScrollPane2.setViewportView(txtContenido);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(110, 90, 340, 70);

        txtTitulo.setColumns(20);
        txtTitulo.setRows(5);
        jScrollPane3.setViewportView(txtTitulo);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(110, 50, 340, 30);
        jPanel3.add(cbxTipoNoticia);
        cbxTipoNoticia.setBounds(110, 170, 340, 30);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelar);
        btnCancelar.setBounds(280, 220, 100, 30);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(btnGuardar);
        btnGuardar.setBounds(100, 220, 110, 30);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(30, 210, 430, 10);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 250, 490, 260);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(310, 220, 73, 23);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar);
        btnEditar.setBounds(220, 220, 73, 23);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo);
        btnNuevo.setBounds(140, 220, 63, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 530, 520);

        setSize(new java.awt.Dimension(546, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (Utilidades.isEmpty(txtTitulo.getText()) || Utilidades.isEmpty(txtContenido.getText())) {
            UtilidadesComponente.mensajeError("Error", "Todos los campos son obligatorios");
        } else {
            cargarObjeto();
            if (sn.obtenerNoticia().getId() != null) {
                //Modificar
                if (sn.guardar()) {
                    UtilidadesComponente.mensajeOK("Aviso", "Se ha modificado correctamente");
                    limpiar();
                    cargarTabla();
                } else {
                    UtilidadesComponente.mensajeError("Error", "No se ha podido modificar");
                }
            } else {
                //Guardar
                if (sn.guardar()) {
                    UtilidadesComponente.mensajeOK("Aviso", "Se ha guardado correctamente");
                    limpiar();
                    cargarTabla();
                } else {
                    UtilidadesComponente.mensajeError("Error", "No se ha podido guardar");
                }
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        buscar();
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        cargarEdicion();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void tblNoticiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNoticiasMouseClicked
        if (evt.getClickCount() >= 2) {
            cargarEdicion();
        }
    }//GEN-LAST:event_tblNoticiasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNoticias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNoticias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNoticias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNoticias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmNoticias dialog = new FrmNoticias(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxTipoNoticia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblNoticias;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextArea txtContenido;
    private javax.swing.JTextArea txtTitulo;
    // End of variables declaration//GEN-END:variables
}
