package vista;

import java.awt.event.KeyEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import vista.utilitario.Utilitario;

public class FrmAdministrador extends javax.swing.JDialog {

    Utilitario u = new Utilitario();

    /**
     * Creates new form FrmAdministrador
     */
    public FrmAdministrador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        ButtonGroup botonGrupo = new ButtonGroup();
        botonGrupo.add(rbCajero);
        botonGrupo.add(rbSerCliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAction1 = new org.edisoncor.gui.button.ButtonAction();
        brightPassFilter1 = new org.edisoncor.gui.util.BrightPassFilter();
        buttonAction2 = new org.edisoncor.gui.button.ButtonAction();
        buttonPopup1 = new org.edisoncor.gui.button.ButtonPopup();
        buttonNice1 = new org.edisoncor.gui.button.ButtonNice();
        buttonIpod1 = new org.edisoncor.gui.button.ButtonIpod();
        buttonIcon1 = new org.edisoncor.gui.button.ButtonIcon();
        buttonColoredAction1 = new org.edisoncor.gui.button.ButtonColoredAction();
        buttonTask1 = new org.edisoncor.gui.button.ButtonTask();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();
        labelCustom1 = new org.edisoncor.gui.label.LabelCustom();
        labelHeader1 = new org.edisoncor.gui.label.LabelHeader();
        labelRect1 = new org.edisoncor.gui.label.LabelRect();
        textFieldRectBackground1 = new org.edisoncor.gui.textField.TextFieldRectBackground();
        textField1 = new org.edisoncor.gui.textField.TextField();
        textFieldRectIcon1 = new org.edisoncor.gui.textField.TextFieldRectIcon();
        textFieldRectImage1 = new org.edisoncor.gui.textField.TextFieldRectImage();
        jPanel1 = new javax.swing.JPanel();
        lblDireccion = new org.edisoncor.gui.label.LabelMetric();
        lblNacionalidad = new org.edisoncor.gui.label.LabelMetric();
        lblCedula = new org.edisoncor.gui.label.LabelMetric();
        lblNombre_ = new org.edisoncor.gui.label.LabelMetric();
        btnSalirE = new org.edisoncor.gui.button.ButtonAction();
        txtTelefono = new org.edisoncor.gui.textField.TextFieldRound();
        txtNacionalidad = new org.edisoncor.gui.textField.TextFieldRound();
        txtApellido = new org.edisoncor.gui.textField.TextFieldRound();
        txtNombre = new org.edisoncor.gui.textField.TextFieldRound();
        lblCorreo = new org.edisoncor.gui.label.LabelMetric();
        lblTelefono = new org.edisoncor.gui.label.LabelMetric();
        lblApellido4 = new org.edisoncor.gui.label.LabelMetric();
        txtCorreo = new org.edisoncor.gui.textField.TextFieldRound();
        txtDireccion = new org.edisoncor.gui.textField.TextFieldRound();
        txtCedula = new org.edisoncor.gui.textField.TextFieldRound();
        rbCajero = new javax.swing.JRadioButton();
        rbSerCliente = new javax.swing.JRadioButton();
        btnGuardar = new org.edisoncor.gui.button.ButtonAction();
        lblNombre_1 = new org.edisoncor.gui.label.LabelMetric();
        lblFondo = new javax.swing.JLabel();

        buttonAction1.setText("buttonAction1");

        buttonAction2.setText("buttonAction2");

        buttonPopup1.setText("buttonPopup1");

        buttonNice1.setText("buttonNice1");

        buttonIpod1.setText("buttonIpod1");

        buttonIcon1.setText("buttonIcon1");

        buttonColoredAction1.setText("buttonColoredAction1");

        labelMetric1.setText("labelMetric1");

        labelCustom1.setText("labelCustom1");

        labelHeader1.setText("labelHeader1");

        labelRect1.setText("labelRect1");

        textFieldRectBackground1.setText("textFieldRectBackground1");

        textField1.setText("textField1");

        textFieldRectIcon1.setText("textFieldRectIcon1");

        textFieldRectImage1.setText("textFieldRectImage1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema Bancario \"Doña Bachita\"");
        setIconImage(u.getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        lblDireccion.setText("Direccion");
        jPanel1.add(lblDireccion);
        lblDireccion.setBounds(40, 210, 87, 17);

        lblNacionalidad.setText("Nacionalidad");
        jPanel1.add(lblNacionalidad);
        lblNacionalidad.setBounds(37, 130, 90, 17);

        lblCedula.setText("Cedula");
        jPanel1.add(lblCedula);
        lblCedula.setBounds(40, 170, 87, 17);

        lblNombre_.setText("Nombre");
        jPanel1.add(lblNombre_);
        lblNombre_.setBounds(40, 50, 87, 17);

        btnSalirE.setBackground(new java.awt.Color(0, 51, 204));
        btnSalirE.setText("Salir");
        btnSalirE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirEActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalirE);
        btnSalirE.setBounds(360, 240, 116, 35);

        txtTelefono.setBackground(new java.awt.Color(0, 51, 204));
        txtTelefono.setForeground(new java.awt.Color(255, 255, 255));
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelefono);
        txtTelefono.setBounds(160, 280, 200, 30);

        txtNacionalidad.setBackground(new java.awt.Color(0, 51, 204));
        txtNacionalidad.setForeground(new java.awt.Color(255, 255, 255));
        txtNacionalidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNacionalidadKeyTyped(evt);
            }
        });
        jPanel1.add(txtNacionalidad);
        txtNacionalidad.setBounds(160, 120, 200, 30);

        txtApellido.setBackground(new java.awt.Color(0, 51, 204));
        txtApellido.setForeground(new java.awt.Color(255, 255, 255));
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(txtApellido);
        txtApellido.setBounds(160, 80, 200, 30);

        txtNombre.setBackground(new java.awt.Color(0, 51, 204));
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombre);
        txtNombre.setBounds(160, 41, 200, 30);

        lblCorreo.setText("Correo");
        jPanel1.add(lblCorreo);
        lblCorreo.setBounds(40, 250, 87, 17);

        lblTelefono.setText("Telefono");
        jPanel1.add(lblTelefono);
        lblTelefono.setBounds(40, 290, 87, 17);

        lblApellido4.setText("Apellido");
        jPanel1.add(lblApellido4);
        lblApellido4.setBounds(40, 90, 87, 17);

        txtCorreo.setBackground(new java.awt.Color(0, 51, 204));
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoFocusLost(evt);
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCorreo);
        txtCorreo.setBounds(160, 240, 200, 30);

        txtDireccion.setBackground(new java.awt.Color(0, 51, 204));
        txtDireccion.setForeground(new java.awt.Color(255, 255, 255));
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });
        jPanel1.add(txtDireccion);
        txtDireccion.setBounds(160, 200, 200, 30);

        txtCedula.setBackground(new java.awt.Color(0, 51, 204));
        txtCedula.setForeground(new java.awt.Color(255, 255, 255));
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCedula);
        txtCedula.setBounds(160, 160, 200, 30);

        rbCajero.setBackground(new java.awt.Color(0, 51, 204));
        rbCajero.setForeground(new java.awt.Color(255, 255, 255));
        rbCajero.setSelected(true);
        rbCajero.setText("Cajero");
        jPanel1.add(rbCajero);
        rbCajero.setBounds(160, 330, 80, 23);

        rbSerCliente.setBackground(new java.awt.Color(0, 51, 204));
        rbSerCliente.setForeground(new java.awt.Color(255, 255, 255));
        rbSerCliente.setText("Ser. Cliente");
        jPanel1.add(rbSerCliente);
        rbSerCliente.setBounds(280, 330, 100, 23);

        btnGuardar.setBackground(new java.awt.Color(0, 51, 204));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar);
        btnGuardar.setBounds(360, 180, 116, 35);

        lblNombre_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre_1.setText("Registrar Personal");
        jPanel1.add(lblNombre_1);
        lblNombre_1.setBounds(137, 7, 220, 30);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/wallpapers/all-blue-wallpaper-9.jpg"))); // NOI18N
        lblFondo.setText("Cajero");
        jPanel1.add(lblFondo);
        lblFondo.setBounds(0, 0, 490, 370);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 370));

        setSize(new java.awt.Dimension(507, 403));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirEActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirEActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        u.verificadorTexto(evt);
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void txtNacionalidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNacionalidadKeyTyped
        u.verificadorTexto(evt);
    }//GEN-LAST:event_txtNacionalidadKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        u.verificadorTexto(evt);
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        u.verificadorTexto(evt);
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        u.verificadorNumeros(txtTelefono.getText(), evt);
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusLost
//        u.verificadorEmail(txtCorreo.getText());
//        if(!u.isEmail(txtCorreo.getText())){
//            txtCorreo.setText(null);
//        }
    }//GEN-LAST:event_txtCorreoFocusLost

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        u.verificadorCedula(txtCedula.getText());
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        u.verificadorEmail(txtCorreo.getText());
        if (!u.isEmail(txtCorreo.getText())) {
            txtCorreo.setText(null);
        }
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmAdministrador dialog = new FrmAdministrador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.util.BrightPassFilter brightPassFilter1;
    private org.edisoncor.gui.button.ButtonAction btnGuardar;
    private org.edisoncor.gui.button.ButtonAction btnSalirE;
    private org.edisoncor.gui.button.ButtonAction buttonAction1;
    private org.edisoncor.gui.button.ButtonAction buttonAction2;
    private org.edisoncor.gui.button.ButtonColoredAction buttonColoredAction1;
    private org.edisoncor.gui.button.ButtonIcon buttonIcon1;
    private org.edisoncor.gui.button.ButtonIpod buttonIpod1;
    private org.edisoncor.gui.button.ButtonNice buttonNice1;
    private org.edisoncor.gui.button.ButtonPopup buttonPopup1;
    private org.edisoncor.gui.button.ButtonTask buttonTask1;
    private javax.swing.JPanel jPanel1;
    private org.edisoncor.gui.label.LabelCustom labelCustom1;
    private org.edisoncor.gui.label.LabelHeader labelHeader1;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    private org.edisoncor.gui.label.LabelRect labelRect1;
    private org.edisoncor.gui.label.LabelMetric lblApellido4;
    private org.edisoncor.gui.label.LabelMetric lblCedula;
    private org.edisoncor.gui.label.LabelMetric lblCorreo;
    private org.edisoncor.gui.label.LabelMetric lblDireccion;
    private javax.swing.JLabel lblFondo;
    private org.edisoncor.gui.label.LabelMetric lblNacionalidad;
    private org.edisoncor.gui.label.LabelMetric lblNombre_;
    private org.edisoncor.gui.label.LabelMetric lblNombre_1;
    private org.edisoncor.gui.label.LabelMetric lblTelefono;
    private javax.swing.JRadioButton rbCajero;
    private javax.swing.JRadioButton rbSerCliente;
    private org.edisoncor.gui.textField.TextField textField1;
    private org.edisoncor.gui.textField.TextFieldRectBackground textFieldRectBackground1;
    private org.edisoncor.gui.textField.TextFieldRectIcon textFieldRectIcon1;
    private org.edisoncor.gui.textField.TextFieldRectImage textFieldRectImage1;
    private org.edisoncor.gui.textField.TextFieldRound txtApellido;
    private org.edisoncor.gui.textField.TextFieldRound txtCedula;
    private org.edisoncor.gui.textField.TextFieldRound txtCorreo;
    private org.edisoncor.gui.textField.TextFieldRound txtDireccion;
    private org.edisoncor.gui.textField.TextFieldRound txtNacionalidad;
    private org.edisoncor.gui.textField.TextFieldRound txtNombre;
    private org.edisoncor.gui.textField.TextFieldRound txtTelefono;
    // End of variables declaration//GEN-END:variables
}
